[toolchain]

[features]
resolution = true
skip-lint = false

[programs.testnet]
flipsonicprogram = "edJUEE32ixRxvoiCfVD9Svo5yaSrTNrgxrYDfEVyo1Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.sonic.game/"
wallet = "./7e8EC4BuPiEnajQ6V86Y8pWs4TJuiz5xCFxD9uXYMQaL.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
