[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
flipsonicprogram = "eJ4nfcgfmDQdv2RrcDdijaJmDCicRqHKGGUgPJjBLcm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./7e8EC4BuPiEnajQ6V86Y8pWs4TJuiz5xCFxD9uXYMQaL.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
